export const PATH = {
  API: "/api/v1",
  REGISTER: "/register",
  LOGIN: "/login",
  REFRESH: "/refresh",
  LOGOUT: "/logout",
  GET_ALL_USERS: "/users/all",
  GET_USER_BY_USER_ID: "/users/:user_id",
  UPDATE_USER_BY_USER_ID: "/user/edit/:user_id",
  GET_ALL_SERVICES: "/services/all",
  GET_SERVICE_BY_ID: "/service/:service_id",
  CREATE_SERVICE: "/create/service",
  EDIT_SERVICE_BY_ID: "/service/edit/:service_id",
  DELETE_SERVICE_BY_ID: "/service/delete/:service_id",
};
