export const PATH = {
  API: "/api/v1",
  REGISTER: "/register",
  LOGIN: "/login",
  REFRESH: "/refresh",
  LOGOUT: "/logout",
  USERS: "/users",
  USER_ID: "/users/:id",
  EDIT_USER_ID: "/user/edit/:id",
  SERVICES: "/services",
  SERVICE_ID: "/service/:id",
  EDIT_SERVICE_ID: "/service/edit/:id",
  TIMESLOTS: "/timeslots",
  TIMESLOT_ID: "/timeslot/:id",
  EDIT_TIMESLOT_ID: "/timeslot/edit/:id",
};
